# **TFM Explainable Fuzzy AI**

## **Subtítulo**

***Autor:*** Jorge Montesinos Bravo  
***Tutor:*** Mercedes Valdés Vela

***Fecha:*** 99/05/2026

In [1]:
from sklearn.datasets import make_classification, make_regression, make_blobs
import pandas as pd
import numpy as np
from faker import Faker

## Generación de Datos Sintéticos con sklearn

In [2]:
# Generar 1000 muestras con 4 variables (2 útiles para el modelo)
X, y = make_classification(
    n_samples=1000, 
    n_features=4, 
    n_informative=2, 
    n_redundant=0, 
    n_classes=2, 
    random_state=42
)

# Convertir a un DataFrame de Pandas para mejor visualización
df = pd.DataFrame(X, columns=['Variable_1', 'Variable_2', 'Variable_3', 'Variable_4'])
df['Objetivo'] = y
print(df.head())

   Variable_1  Variable_2  Variable_3  Variable_4  Objetivo
0    2.142482   -0.235970    1.951446    0.744186         1
1   -0.778978   -0.103255   -0.748500   -1.643189         0
2   -1.445993    0.570613   -2.144482    0.968185         0
3    0.211180    0.277358    0.223430   -0.022279         1
4   -0.754405    0.552300    1.045959    0.625631         1

In [7]:
df

     Variable_1  Variable_2  Variable_3  Variable_4  Objetivo
0      2.142482   -0.235970    1.951446    0.744186         1
1     -0.778978   -0.103255   -0.748500   -1.643189         0
2     -1.445993    0.570613   -2.144482    0.968185         0
3      0.211180    0.277358    0.223430   -0.022279         1
4     -0.754405    0.552300    1.045959    0.625631         1
..          ...         ...         ...         ...       ...
995    0.594676    0.950016    0.465225    0.243005         1
996   -0.086013    0.731380   -0.055715    0.590422         1
997   -1.225096   -0.606865   -0.900324    0.457687         1
998    1.529300   -1.656623   -0.719421   -0.524448         0
999    1.287152    0.532006   -1.368791    0.361661         0

[1000 rows x 5 columns]

## Generación de Datos Sintéticos con pandas y numpy

In [3]:
# Fijar semilla para reproducibilidad
np.random.seed(42)

# Generar 500 registros
n_registros = 500

datos = {
    'Edad': np.random.randint(18, 65, n_registros),
    'Ingresos': np.random.normal(50000, 15000, n_registros), # Distribución normal
    'Categoria': np.random.choice(['A', 'B', 'C'], n_registros, p=[0.5, 0.3, 0.2]),
    # Variable objetivo basada en una regla lógica con ruido introducido
    'Compra': np.where(np.random.rand(n_registros) > 0.3, 1, 0) 
}

df_custom = pd.DataFrame(datos)
print(df_custom.describe())

             Edad      Ingresos      Compra
count  500.000000    500.000000  500.000000
mean    41.278000  49879.637465    0.698000
std     13.389072  14815.028192    0.459585
min     18.000000   9546.700356    0.000000
25%     30.000000  39491.176441    0.000000
50%     42.000000  49718.529921    1.000000
75%     52.000000  59454.853493    1.000000
max     64.000000  96183.212127    1.000000

In [8]:
df_custom

     Edad      Ingresos Categoria  Compra
0      56  81995.500620         C       1
1      46  20718.683007         B       1
2      32  47723.223574         B       1
3      60  58824.758097         C       1
4      25  54214.878016         A       1
..    ...           ...       ...     ...
495    37  59310.081463         C       0
496    41  52665.515014         B       0
497    29  29969.834619         A       0
498    52  55702.967765         A       1
499    50  59158.786179         A       0

[500 rows x 4 columns]

## Generación de Datos Sintéticos con Faker

In [4]:
fake = Faker('es_ES') # Configurado para español de España
n_registros = 5

datos_usuarios = []
for _ in range(n_registros):
    datos_usuarios.append({
        'Nombre': fake.name(),
        'Ciudad': fake.city(),
        'Trabajo': fake.job(),
        'Email': fake.email()
    })

df_faker = pd.DataFrame(datos_usuarios)
print(df_faker)

                     Nombre      Ciudad  \
0     Estrella del Rocamora      Huelva
1  Ignacio Villalba Bastida       Ávila
2       Azucena Coca Palomo  Las Palmas
3      Laura Llamas Márquez    Valencia
4          Camilo Valcárcel  Valladolid

                                             Trabajo  \
0                Empleado de servicios de transporte
1  Operador de máquinas de preparación de fibras,...
2                                         Periodista
3                               Entrenador deportivo
4      Operador de máquinas de movimiento de tierras

                           Email
0             amor68@example.org
1         candelas65@example.net
2           regina06@example.org
3    uriartefilomena@example.net
4  montserratgimenez@example.org

In [9]:
df_faker

,Nombre,Ciudad,Trabajo,Email
0,Estrella del Rocamora,Huelva,Empleado de servicios de transporte,amor68@example.org
1,Ignacio Villalba Bastida,Ávila,"Operador de máquinas de preparación de fibras,...",candelas65@example.net
2,Azucena Coca Palomo,Las Palmas,Periodista,regina06@example.org
3,Laura Llamas Márquez,Valencia,Entrenador deportivo,uriartefilomena@example.net
4,Camilo Valcárcel,Valladolid,Operador de máquinas de movimiento de tierras,montserratgimenez@example.org